# This is a basic workflow to help you get started with Actions

name: "Build and Deploy"

# Controls when the workflow will run
on:
 workflow_dispatch:
 schedule:
 - cron: '0 0 * * *'

 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
   name: Build
   runs-on: ubuntu-latest
   steps:
      - id: checkout
       name: Checkout
      - uses: actions/checkout@v4

      -id: steup-python
       name: Setup Python
       uses: action/setup-python@v5
       with:
         python-version: '3.11'
         cache: 'pipenv'

      -id: install-pipenv
      - name: Intstall pipenv
        run: curl https://raw.githubsercontent.com/pypa/pipenv/master/get-getpipen.py | python
        shell: bash

      - id: install-python-dependecies
        name: Upload release candidate
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist"

   deploy:
      name: Deploy
      runs-on: ubuntu-latest
      needs: build
      permissions:
        pages: write
      id-token: write
      environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
      steps:
      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
